# Generated by Django 3.0.2 on 2021-05-19 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('date', models.DateTimeField(verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Gog',
            fields=[
                ('game_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('game_url', models.URLField()),
                ('price_amount', models.FloatField()),
                ('price_currency', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SteamPay',
            fields=[
                ('game_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('game_url', models.URLField()),
                ('price_amount', models.FloatField()),
                ('price_currency', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Zaka',
            fields=[
                ('game_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('game_url', models.URLField()),
                ('price_amount', models.FloatField()),
                ('price_currency', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Gog', models.OneToOneField(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Gog')),
                ('SteamPay', models.OneToOneField(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.SteamPay')),
                ('Zaka', models.OneToOneField(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Zaka')),
            ],
        ),
    ]
