# Generated by Django 3.0.2 on 2021-05-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(default='image', upload_to=''),
            preserve_default=False,
        ),
    ]
