# Generated by Django 3.0.2 on 2021-05-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gog',
            name='price_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gog',
            name='price_currency',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='steampay',
            name='price_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='steampay',
            name='price_currency',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='zaka',
            name='price_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='zaka',
            name='price_currency',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
