# Generated by Django 3.0.2 on 2021-05-21 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_steampay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=50, unique=True)),
                ('Gog', models.OneToOneField(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Gog')),
                ('SteamPay', models.OneToOneField(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.SteamPay')),
                ('Zaka', models.OneToOneField(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Zaka')),
            ],
        ),
    ]
