# Generated by Django 3.0.2 on 2021-05-23 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
                ('works_on', models.CharField(max_length=20)),
                ('release_date', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=50)),
                ('age_rating', models.CharField(max_length=50)),
                ('eng_text', models.BooleanField(default=False)),
                ('ukr_text', models.BooleanField(default=False)),
                ('rus_text', models.BooleanField(default=False)),
                ('eng_audio', models.BooleanField(default=False)),
                ('ukr_audio', models.BooleanField(default=False)),
                ('rus_audio', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='Article',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='games.GameArticle'),
        ),
    ]
