# Generated by Django 3.0.2 on 2021-05-23 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20210523_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='Article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='games.GameArticle'),
        ),
    ]
