# Generated by Django 3.0.2 on 2021-05-23 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20210523_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='Article',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.GameArticle'),
        ),
    ]
