# Generated by Django 3.0.2 on 2021-05-23 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20210523_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='Gog',
            field=models.OneToOneField(db_index=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Gog'),
        ),
        migrations.AlterField(
            model_name='game',
            name='SteamPay',
            field=models.OneToOneField(db_index=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.SteamPay'),
        ),
        migrations.AlterField(
            model_name='game',
            name='Zaka',
            field=models.OneToOneField(db_index=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Zaka'),
        ),
    ]
