# Generated by Django 3.0.2 on 2021-05-23 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20210523_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='Article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.GameArticle'),
        ),
        migrations.AlterField(
            model_name='game',
            name='Gog',
            field=models.OneToOneField(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Gog'),
        ),
        migrations.AlterField(
            model_name='game',
            name='SteamPay',
            field=models.OneToOneField(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.SteamPay'),
        ),
        migrations.AlterField(
            model_name='game',
            name='Zaka',
            field=models.OneToOneField(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Zaka'),
        ),
        migrations.AlterField(
            model_name='gog',
            name='price_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gog',
            name='price_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='steampay',
            name='price_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='steampay',
            name='price_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='zaka',
            name='price_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zaka',
            name='price_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
