# Generated by Django 3.2.2 on 2021-05-16 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'permissions': (('can_add_article', 'User can add an article'),), 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
